[package]
name = "cargo-mirage"
version = "0.1.0"
authors = ["Sam De Roeck <sadroeck@gmail.com>"]

[dependencies]
futures = "0.1.x"
actix-web = "0.6.x"
actix = "0.5.x"
toml = "0.4.x"
serde = "1.0.x"
serde_derive = "1.0.x"
clap = "2.31.x"
